---
name: "build-executables"

# Configures this workflow
on:
  push: 
    branches:
      - main
  pull_request:
    # types: [ opened, synchronize ]
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:  # Allows manual execution

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

# Available machines:
# https://github.com/actions/runner-images/tree/main

jobs:
  Linux_GCC14_64bit:
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm ]
    runs-on: ${{ matrix.os }}
    outputs:
      artid: ${{ steps.artifact-upload-step.outputs.artifact-id }}
      arturl: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - name: Checkout LandSandBoat server
      uses: actions/checkout@v4
      with:
        repository: LandSandBoat/server
        submodules: 'recursive'
        fetch-depth: 1

    - name: Install Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y software-properties-common cmake libmariadb-dev-compat libluajit-5.1-dev \
        libzmq3-dev zlib1g-dev libssl-dev binutils-dev curl jq git gcc-14 g++-14 libgcc-14-dev

    - name: Cache 'build' folder
      uses: actions/cache@v4
      with:
        path: build
        key: ${{ matrix.os }}-GCC14-64bit

    - name: Configure CMake
      run: |
        echo "LSB_SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "OS_ARCH_TYPE=$(uname -p)" >> $GITHUB_ENV
        echo "OS_TYPE=$(uname)" >> $GITHUB_ENV
        export CC=/usr/bin/gcc-14
        export CXX=/usr/bin/g++-14
        sed -i 's/if ((c >= 0 && c <= 0x20) || c >= 0x7F)/if (!std::isprint(static_cast<unsigned char>(c)))/' src/map/lua/luautils.cpp
        if [ $(uname -p) = "x86_64" ]; then CFLAGS=-m64 CXXFLAGS=-m64 LDFLAGS=-m64 cmake -S . -B build ; fi
        if [ $(uname -p) = "aarch64" ]; then cmake -S . -B build ; fi
    - name: Build
      run: |
        cmake --build build -j4
        curl -sLO $(curl -s "https://api.github.com/repos/LandSandBoat/xiloader/releases" | jq -r '.[0].assets.[].browser_download_url')
        chmod +x xi_connect xi_map xi_search xi_world

    - name: Archive PR Executables
      if: ${{ github.ref_name != 'main' }}
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: ${{ env.OS_TYPE }}_${{ env.LSB_SHORT_HASH }}_${{ env.OS_ARCH_TYPE }}
        retention-days: 1
        overwrite: true
        path: |
          xiloader.exe
          xi_connect
          xi_map
          xi_search
          xi_world

    - name: Append Run 
      if: ${{ github.ref_name != 'main' }}
      run: |
        gh pr comment --body "${{ env.OS_TYPE }}_${{ env.LSB_SHORT_HASH }}_${{ env.OS_ARCH_TYPE }}: ${{ steps.artifact-upload-step.outputs.artifact-url }}"
      env:
        GH_TOKEN: ${{ github.token }}
    
    - name: Archive Main Executables
      if: ${{ github.ref_name == 'main' }}
      uses: actions/upload-artifact@v4
      id: artifact-upload-main
      with:
        name: ${{ env.OS_TYPE }}_${{ env.LSB_SHORT_HASH }}_${{ env.OS_ARCH_TYPE }}
        retention-days: 7
        overwrite: true
        path: |
          xiloader.exe
          xi_connect
          xi_map
          xi_search
          xi_world
