---
name: "check-lsb-version"

on:
  schedule:
    - cron: "0 0,4,20 * * *"  # Runs over 8 hours, and then rests. 
  workflow_dispatch:  # Allows manual execution

permissions:
  contents: write
  pull-requests: write

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout LandSandBoat Server
        uses: actions/checkout@v4
        with:
          repository: LandSandBoat/server
          # submodules: 'recursive' / Not TODAY!
          fetch-depth: 1
          path: 'lite_server'

      - name: Extract Git Version
        id: git_version
        run: |
          pushd lite_server
          VERSION=$(git log -1 --pretty=format:"%h")
          popd
          rm -rf lite_server
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Config git
        id: cfg_git
        run: |
          # Configure
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
        
      - name: Reset to Main Branch
        id: main_branch
        run: |
          # Grabs All branches
          git fetch --all
          # Checks out the Base/Main Branch
          git checkout main
          # Create a new branch for remotes

      - name: Branch Decision point
        id: decision_branch
        run: |
          PR_EXISTS=$(gh pr list --repo ${{ github.repository }} --search ${{ env.VERSION }} -s all --json title --jq ".[].title" )
          if [ -n "$PR_EXISTS" ]; then
            echo "PR_FOUND=true" >> $GITHUB_ENV
          else
            echo "PR_FOUND=false" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Asset Commit
        if: env.PR_FOUND == 'false'
        run: |
          # Create a new branch for remotes
          git checkout -b lsb-ffxi-${{ env.VERSION }}
          # Create & Add our assets
          echo "${{ env.VERSION }}" > VERSION
          echo "Version: ${{ env.VERSION }} Date: $(date)" >> VERSION_CHANGELOG
          git add VERSION VERSION_CHANGELOG
          # Commit Materials
          git commit -m "Update to version ${{ env.VERSION }}"

      - name: Create PR if version doesn't exist in PRs
        if: env.PR_FOUND == 'false'
        run: |
          # Commit our Branch to our Remote
          git push origin lsb-ffxi-${{ env.VERSION }}
          # Open the PR ?
          gh pr create --base main --head lsb-ffxi-${{ env.VERSION }} --title "Ffxi LSB v${{ env.VERSION }}" --body "Update to version ${{ env.VERSION }}"
          gh workflow run build-executables.yml --ref lsb-ffxi-${{ env.VERSION }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}